version: '3.8'

services:
  # api:
  #   build:
  #     context: ./model_api
  #   container_name: api
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./model_api:/app
  #   environment:
  #     - MODEL_PATH=/app/knn_model.pkl
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #   depends_on:
  #     - cache
  
  cache:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"

  mlflow:
    build:
      context: ./mlflow
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - ARTIFACT_ROOT=/mlflow/mlruns
  
  clickhouse:
    image: "clickhouse/clickhouse-server"
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
  clickhouse_data: