version: '3.8'

services:
  api:
    build:
      context: ./model_api
    container_name: api
    ports:
      - "8080:8080"
    volumes:
      - ./model_api:/app
    environment:
      - MODEL_PATH=/app/knn_model.pkl
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - cache
  
  cache:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
